=== SP7-Ritmare/starterkit/src/geosk/static/EDI-NG_client/templates/edi_template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
  xmlns:xml="http://www.w3.org/XML/1998/namespace" elementFormDefault="qualified"
  vc:minVersion="1.1" attributeFormDefault="qualified">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
    schemaLocation="http://www.w3.org/2001/xml.xsd"/>
  <xs:element name="template">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="settings"/>
        <xs:element ref="endpointTypes"/>
        <xs:element ref="datasources"/>
        <xs:element maxOccurs="unbounded" ref="group"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="endpointTypePK">
      <xs:selector xpath="endpointTypes/endpointType"></xs:selector>
      <xs:field xpath="./@xml:id"></xs:field>
    </xs:key>
    <xs:keyref name="codeListEndpointTypeFK" refer="endpointTypePK">
      <xs:selector xpath="datasources/codelist"></xs:selector>
      <xs:field xpath="./@endpointType"></xs:field>
    </xs:keyref>
    <xs:keyref name="singletonEndpointTypeFK" refer="endpointTypePK">
      <xs:selector xpath="datasources/singleton"></xs:selector>
      <xs:field xpath="./@endpointType"></xs:field>
    </xs:keyref>
    <xs:keyref name="sparqlEndpointTypeFK" refer="endpointTypePK">
      <xs:selector xpath="datasources/sparql"></xs:selector>
      <xs:field xpath="./@endpointType"></xs:field>
    </xs:keyref>    
    
    <xs:key name="datasourcePK">
      <xs:selector xpath="datasources/*"></xs:selector>
      <xs:field xpath="./@xml:id"></xs:field>
    </xs:key>
    <xs:keyref name="datasourceFK" refer="datasourcePK">
      <xs:selector xpath="group/element/produces/item"></xs:selector>
      <xs:field xpath="./@datasource"></xs:field>
    </xs:keyref>    
    
    <xs:key name="elementPK">
      <xs:selector xpath="group/element"></xs:selector>
      <xs:field xpath="./@xml:id"></xs:field>
    </xs:key>
    
  </xs:element>
  <xs:element name="settings">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="userInterfaceLanguage" minOccurs="0"/>
        <xs:element ref="metadataLanguage" minOccurs="0"/>
        <xs:element ref="metadataEndpoint" minOccurs="1"/>
        <xs:element ref="sparqlEndpoint" minOccurs="1"/>
        <xs:element ref="requiresValidation" minOccurs="1"/>
        <xs:element ref="baseDocument" minOccurs="1"/>
        <xs:element ref="xsltChain" minOccurs="1"/>
        <xs:element ref="codelistQuery" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="userInterfaceLanguage">
    <xs:complexType>
      <xs:attribute ref="xml:lang" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="metadataLanguage">
    <xs:complexType>
      <xs:attribute name="selectionItem" use="required" type="xs:IDREF"/>
      <!-- <xs:attribute ref="xml:lang" use="required"/> -->
    </xs:complexType>
  </xs:element>
  <xs:element name="metadataEndpoint" type="xs:anyURI"/>
  <xs:element name="sparqlEndpoint" type="xs:anyURI"/>
  <xs:element name="requiresValidation" type="xs:boolean"/>
  <xs:element name="baseDocument" type="xs:string"/>
  <xs:element name="xsltChain">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element ref="xslt"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="xslt" type="xs:anyURI"/>
  <xs:element name="codelistQuery" type="xs:string"/>
  <xs:element name="endpointTypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="endpointType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="endpointType">
    <xs:complexType>
      <xs:sequence>
        <!-- <xs:element name="id"  minOccurs="0"></xs:element> -->
        <xs:element ref="parameters"/>
      </xs:sequence>
      <xs:attribute ref="xml:id" use="required"/>
      <xs:attribute name="method" use="required" type="xs:NCName"/>
      <xs:attribute name="queryParameter" use="required" type="xs:NCName"/>
    </xs:complexType>
    <!-- 
    <xs:key name="endpointTypeID">
      <xs:selector xpath="endpointType/id" />
      <xs:field xpath="."></xs:field>
    </xs:key>
-->
  </xs:element>
  <xs:element name="parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="parameter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="parameter">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="value" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="datasources">
    <xs:complexType>
      <xs:all>
        <xs:element maxOccurs="unbounded" ref="codelist"/>
        <xs:element maxOccurs="unbounded" ref="sparql"/>
        <xs:element maxOccurs="unbounded" ref="singleton"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="codelist">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="uri"/>
        <xs:element ref="url" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="endpointType" use="required" type="xs:string"/>
      <xs:attribute ref="xml:id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="uri" type="xs:anyURI"/>
  <xs:element name="sparql">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="query"/>
        <xs:element ref="url" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="endpointType" use="required" type="xs:string"/>
      <xs:attribute ref="xml:id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="singleton">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="query"/>
        <xs:element ref="url" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="endpointType" use="required" type="xs:string"/>
      <xs:attribute name="triggerItem" use="optional" type="xs:NCName"/>
      <xs:attribute ref="xml:id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="help"/>
          <xs:element ref="label"/>
          <xs:element maxOccurs="unbounded" ref="element"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute ref="xml:id" use="required"/>
    </xs:complexType>
    <xs:key name="ID">
      <xs:selector xpath="element"/>
      <xs:field xpath="@xml:id"/>
    </xs:key>
    <xs:keyref name="IDREF" refer="ID">
      <xs:selector xpath="element"/>
      <xs:field xpath="@alternativeTo"/>
    </xs:keyref>
    
  </xs:element>
  <xs:element name="element">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="help"/>
          <xs:element ref="label"/>
          <xs:element ref="hasRoot"/>
        </xs:choice>
        <xs:element ref="produces"/>
      </xs:sequence>
      <xs:attribute name="isMandatory" use="required" type="xs:boolean"/>
      <xs:attribute name="isMultiple" use="required" type="xs:boolean"/>
      <xs:attribute ref="xml:id" use="required"/>
      <xs:attribute name="alternativeTo" use="optional" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="hasRoot" type="xs:string"/>
  <xs:element name="produces">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="item"/>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="itemPK">
      <xs:selector xpath="item"></xs:selector>
      <xs:field xpath="./@hasIndex"></xs:field>
    </xs:key>
    
  </xs:element>
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="help" minOccurs="0"/>
          <xs:element ref="label" minOccurs="0"/>
        </xs:choice>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="hasPath" minOccurs="0"/>
          <xs:group ref="boundingBox"/>
          <xs:group ref="dateRange"/>
          <xs:element ref="defaultValue" minOccurs="0"/>
          <xs:element ref="hasValue" minOccurs="0"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="show" use="optional"/>
      <xs:attribute name="datasource" type="xs:string"/>
      <xs:attribute name="hasDatatype" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="string" />
            <xs:enumeration value="codelist" />
            <xs:enumeration value="ref" />
            <xs:enumeration value="autoCompletion" />
            <xs:enumeration value="select" />
            <xs:enumeration value="URI" />
            <xs:enumeration value="date" />
            <xs:enumeration value="text" />
            <xs:enumeration value="int" />
            <xs:enumeration value="boundingBox" />
            <xs:enumeration value="dateRange" />
            <xs:enumeration value="autonumber" />
            <xs:enumeration value="URN" />
            <xs:enumeration value="URI" />
            <xs:enumeration value="URL" />
            <xs:enumeration value="function" />
            <xs:enumeration value="sensorID" />
            <xs:enumeration value="string" />
            <xs:enumeration value="boolean" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="hasIndex" use="required" type="xs:integer"/>
      <xs:attribute ref="xml:id" use="required"/>
      <xs:attribute name="isFixed" use="required" type="xs:boolean"/>
      <xs:attribute name="field" use="optional"/>
      <xs:attribute name="outIndex" type="xs:integer"/>
      <xs:attribute name="isLanguageNeutral"></xs:attribute>
      <xs:attribute name="queryStringParameter"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="hasPath" type="xs:anyURI"/>
  <xs:element name="defaultValue" type="xs:anyType"/>
  <xs:element name="field" type="xs:NCName"/>
  <xs:element name="hasValue" type="xs:string"/>
  <xs:element name="url" type="xs:anyURI"/>
  <xs:element name="query" type="xs:string"/>

  <xs:group name="boundingBox">
    <xs:sequence>
      <xs:element name="westLongitude" type="geoCoord" minOccurs="1"/>
      <xs:element name="eastLongitude" type="geoCoord" minOccurs="1"/>
      <xs:element name="northLatitude" type="geoCoord" minOccurs="1"/>
      <xs:element name="southLatitude" type="geoCoord" minOccurs="1"/>
    </xs:sequence>
  </xs:group>
  <xs:group name="dateRange">
    <xs:sequence>
      <xs:element name="start" minOccurs="1"/>
      <xs:element name="end" minOccurs="1"/>
    </xs:sequence>
  </xs:group>
  <xs:complexType name="geoCoord">
    <xs:sequence maxOccurs="unbounded">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="help" minOccurs="0"/>
        <xs:element ref="label" minOccurs="0"/>
        <xs:element ref="hasPath" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="outIndex" use="optional" type="xs:integer"/>
    <xs:attribute name="queryStringParameter" use="optional" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="date">
    <xs:sequence maxOccurs="unbounded">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="help" minOccurs="0"/>
        <xs:element ref="label" minOccurs="0"/>
        <xs:element ref="hasPath" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="outIndex" use="optional" type="xs:integer"/>
    <xs:attribute name="queryStringParameter" use="optional" type="xs:string"/>
  </xs:complexType>

  <xs:element name="label">
    <xs:complexType mixed="true">
      <xs:attribute ref="xml:lang" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="help">
    <xs:complexType mixed="true">
      <xs:attribute ref="xml:lang" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SP7-Ritmare/starterkit/src/geosk/static/EDI-NG_client/templates/SensorML20_vesselCompHistory_v1.00_newEdiSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="edi_template.xsd">
    <settings>
        <userInterfaceLanguage xml:lang="en"/>
        <!--<metadataLanguage selectionItem="ling_md_1"/>-->
        <metadataEndpoint>/metadata/</metadataEndpoint>
        <sparqlEndpoint>/sparql/</sparqlEndpoint>
        <requiresValidation>true</requiresValidation>
        <baseDocument><![CDATA[
            
       <sml:EventList xmlns:sml="http://www.opengis.net/sensorml/2.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:swe="http://www.opengis.net/swe/2.0"
    xmlns:gml="http://www.opengis.net/gml/3.2"
    xmlns:xlink="http://www.w3.org/1999/xlink"
            xsi:schemaLocation=" http://www.opengis.net/sensorML/2.0 http://schemas.opengis.net/sensorML/2.0/sensorML.xsd http://www.opengis.net/samplingSpatial/2.0 http://schemas.opengis.net/samplingSpatial/2.0/spatialSamplingFeature.xsd">
    
       </sml:EventList>
        
        ]]></baseDocument>
        <xsltChain>
            <xslt>http://sp7.irea.cnr.it/jboss/MDService/rest/SensorML20_vessel.xsl?version=1.00</xslt>
        </xsltChain>
    </settings>
    <endpointTypes>
        <endpointType xml:id="virtuoso" method="GET" queryParameter="query">
            <parameters>
                <parameter name="format" value="application/sparql-results+json"/>
                <parameter name="save" value="display"/>
                <parameter name="fname" value="undefined"/>
            </parameters>
        </endpointType>
        <endpointType xml:id="nercFuseki" method="GET" queryParameter="query">
            <parameters>
                <parameter name="output" value="json"/>
            </parameters>
        </endpointType>
    </endpointTypes>
    <datasources>
        <singleton xml:id="devices" endpointType="nercFuseki">
            <query><![CDATA[
                PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
                PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
                    SELECT ?c ?l ?a
                    WHERE {
                    ?c rdf:type skos:Concept.
                    <http://vocab.nerc.ac.uk/collection/L22/current/> skos:member ?c.
                    OPTIONAL {
                    ?c skos:prefLabel ?l.
                    FILTER( LANG(?l) = "en")
                    }
                    OPTIONAL {
                    ?c skos:prefLabel ?a.
                    FILTER( LANG(?a) = "it")
                    }
                    FILTER( REGEX( STR(?l), "$search_param", "i") || REGEX( STR(?a), "$search_param", "i") )
                    }
                    ORDER BY ASC(?l) ASC(?a)
            ]]></query>
            <url>/vocabs/edg/tbl/sparql</url>
        </singleton>
        <sparql xml:id="parameters" endpointType="nercFuseki">
            <query><![CDATA[
                PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
                PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
                    SELECT ?c ?l ?a
                    WHERE {
                    ?c rdf:type skos:Concept.
                    <http://vocab.nerc.ac.uk/collection/P01/current/> skos:member ?c.
                    OPTIONAL {
                    ?c skos:prefLabel ?l.
                    FILTER( LANG(?l) = "en")
                    }
                    OPTIONAL {
                    ?c skos:prefLabel ?a.
                    FILTER( LANG(?a) = "it")
                    }
                    FILTER( REGEX( STR(?l), "$search_param", "i") || REGEX( STR(?a), "$search_param", "i") )
                    }
                    ORDER BY ASC(?l) ASC(?a)
            ]]></query>
        </sparql>
        <!-- Codelists -->
        <codelist xml:id="languages" endpointType="virtuoso">
            <uri>http://inspire-registry.jrc.ec.europa.eu/registers/Languages/items</uri>
            <url>/sparql</url>
        </codelist>
    </datasources>

    <!-- Groups -->
    <!-- History description -->
    <group xml:id="historyDesc">
        <label xml:lang="it">Descrizione</label>
        <label xml:lang="en">Description</label>
        <label xml:lang="es">Descripción</label>
        <element isMandatory="false" isMultiple="false" xml:id="desc">
            <hasRoot>/sml:EventList</hasRoot>
            <produces>
                <item hasDatatype="text" hasIndex="1" xml:id="desc_1" isFixed="false">
                    <hasPath>swe:description</hasPath>
                </item>
            </produces>
        </element>
    </group>
    <!-- Event group -->
    <group xml:id="events">
        <label xml:lang="it">Storia composizione strumentale</label>
        <label xml:lang="en">Instrument Composition History</label>
        <label xml:lang="es">Histórico de composición instrumental</label>
        <element xml:id="history" isMandatory="true" isMultiple="true">
            <label xml:lang="it">Strumentazione a bordo</label>
            <label xml:lang="en">Instrument on board</label>
            <label xml:lang="es">Embarque de instrumentación</label>
            <help xml:lang="it">Strumentazione imbarco sulla nave nel tempo (es. modifiche,
                ricalibrazione, ecc.)</help>
            <help xml:lang="en">Instrument in a vessel in time (e.g., calibration, adjustments,
                etc.)</help>
            <help xml:lang="es">Embarque de la instrumentación del buque en el tiempo (p.e, calibración, ajustes, etc.)</help>
            <hasRoot>/sml:EventList</hasRoot>
            <produces>
                <item hasIndex="1" xml:id="history_1" isFixed="false" hasDatatype="text">
                    <label xml:lang="it">Descrizione</label>
                    <label xml:lang="en">Description</label>
                    <label xml:lang="es">Descripción</label>
                    <help xml:lang="it">Breve descrizione</help>
                    <help xml:lang="en">Brief description</help>
                    <help xml:lang="es">Breve descripción</help>
                    <hasPath>sml:event/sml:Event/swe:description</hasPath>
                </item>
                <!-- ISSUE: in this moment only date and not time -->
                <item hasIndex="2" xml:id="history_2" isFixed="false" hasDatatype="dateRange">
                    <label xml:lang="en">Foo</label>
                    <label xml:lang="it">Data</label>
                    <label xml:lang="es">Datos</label>
                    <start>
                        <label xml:lang="en">Begin date</label>
                        <label xml:lang="it">Data inizio</label>
                        <label xml:lang="es">Fecha de inicio</label>
                        <hasPath>sml:event/sml:Event/sml:time/gml:TimePeriod/gml:beginPosition</hasPath>
                    </start>
                    <end>
                        <label xml:lang="en">End date</label>
                        <label xml:lang="it">Data fine</label>
                        <label xml:lang="es">Fecha final</label>
                        <hasPath>sml:event/sml:Event/sml:time/gml:TimePeriod/gml:endPosition</hasPath>
                    </end>
                </item>
                <item hasIndex="3" xml:id="history_3" isFixed="true" hasDatatype="autonumber">
                    <hasPath>sml:event/sml:Event/sml:time/gml:TimePeriod/@gml:id</hasPath>
                    <hasValue>operation_interval_</hasValue>
                </item>
                <item hasIndex="4" xml:id="history_4" isFixed="true" hasDatatype="string">
                    <hasPath>sml:event/sml:Event/sml:property/@xlink:title</hasPath>
                    <hasValue>link to instrument</hasValue>
                </item>
                <item hasIndex="5" xml:id="history_5" isFixed="false" 
                    hasDatatype="autoCompletion" datasource="devices">
                    <label xml:lang="en">Device</label>
                    <label xml:lang="it">Dispositivo</label>
                    <label xml:lang="es">Dispositivo</label>
                    <hasPath>sml:event/sml:Event/sml:property/@xlink:role</hasPath>
                </item>           
                <item hasIndex="6" xml:id="history_6" isFixed="true"
                    datasource="devices" hasDatatype="select" field="c">
                    <hasPath>sml:event/sml:Event/sml:property/@xlink:href</hasPath>
                </item>
            </produces>
        </element>
    </group>
</template>

=== SP7-Ritmare/starterkit/src/geosk/static/EDI-NG_client/templates/SensorML20_vesselEventHistory_v1.00_newEdiSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="edi_template.xsd">
    <settings>
        <userInterfaceLanguage xml:lang="en"/>
        <!--<metadataLanguage selectionItem="ling_md_1"/>-->
        <metadataEndpoint>/metadata/</metadataEndpoint>
        <sparqlEndpoint>/sparql/</sparqlEndpoint>
        <requiresValidation>true</requiresValidation>
        <baseDocument><![CDATA[
            
       <sml:EventList xmlns:sml="http://www.opengis.net/sensorml/2.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:swe="http://www.opengis.net/swe/2.0"
    xmlns:gml="http://www.opengis.net/gml/3.2"
    xmlns:xlink="http://www.w3.org/1999/xlink"
            xsi:schemaLocation=" http://www.opengis.net/sensorML/2.0 http://schemas.opengis.net/sensorML/2.0/sensorML.xsd http://www.opengis.net/samplingSpatial/2.0 http://schemas.opengis.net/samplingSpatial/2.0/spatialSamplingFeature.xsd">
    
       </sml:EventList>
        
        ]]></baseDocument>
        <xsltChain>
            <xslt>http://sp7.irea.cnr.it/jboss/MDService/rest/SensorML20_vessel.xsl?version=1.00</xslt>
        </xsltChain>
    </settings>
    <endpointTypes>
        <endpointType xml:id="virtuoso" method="GET" queryParameter="query">
            <parameters>
                <parameter name="format" value="application/sparql-results+json"/>
                <parameter name="save" value="display"/>
                <parameter name="fname" value="undefined"/>
            </parameters>
        </endpointType>
        <endpointType xml:id="nercFuseki" method="GET" queryParameter="query">
            <parameters>
                <parameter name="output" value="json"/>
            </parameters>
        </endpointType>
    </endpointTypes>
    <datasources>
        <singleton xml:id="devices" endpointType="nercFuseki">
            <query><![CDATA[
                PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
                PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
                    SELECT ?c ?l ?a
                    WHERE {
                    ?c rdf:type skos:Concept.
                    <http://vocab.nerc.ac.uk/collection/L22/current/> skos:member ?c.
                    OPTIONAL {
                    ?c skos:prefLabel ?l.
                    FILTER( LANG(?l) = "en")
                    }
                    OPTIONAL {
                    ?c skos:prefLabel ?a.
                    FILTER( LANG(?a) = "it")
                    }
                    FILTER( REGEX( STR(?l), "$search_param", "i") || REGEX( STR(?a), "$search_param", "i") )
                    }
                    ORDER BY ASC(?l) ASC(?a)
            ]]></query>
            <url>/vocabs/edg/tbl/sparql</url>
        </singleton>
        <sparql xml:id="parameters" endpointType="nercFuseki">
            <query><![CDATA[
                PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
                PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
                    SELECT ?c ?l ?a
                    WHERE {
                    ?c rdf:type skos:Concept.
                    <http://vocab.nerc.ac.uk/collection/P01/current/> skos:member ?c.
                    OPTIONAL {
                    ?c skos:prefLabel ?l.
                    FILTER( LANG(?l) = "en")
                    }
                    OPTIONAL {
                    ?c skos:prefLabel ?a.
                    FILTER( LANG(?a) = "it")
                    }
                    FILTER( REGEX( STR(?l), "$search_param", "i") || REGEX( STR(?a), "$search_param", "i") )
                    }
                    ORDER BY ASC(?l) ASC(?a)
            ]]></query>
        </sparql>
        <!-- Codelists -->
        <codelist xml:id="languages" endpointType="virtuoso">
            <uri>http://inspire-registry.jrc.ec.europa.eu/registers/Languages/items</uri>
            <url>/sparql</url>
        </codelist>
    </datasources>
    
    <!-- Groups -->
    <!-- TO DO: please review all labels and helps without have any connection with calibration other history information -->
    <!-- History description -->
    <group xml:id="historyDesc">
        <label xml:lang="it">Descrizione</label>
        <label xml:lang="en">Description</label>
        <label xml:lang="es">Descripción</label>
        <element isMandatory="false" isMultiple="false" xml:id="desc">
            <hasRoot>/sml:EventList</hasRoot>
            <produces>
                <item hasDatatype="text" hasIndex="1" xml:id="desc_1" isFixed="false">
                    <hasPath>swe:description</hasPath>
                </item>
            </produces>
        </element>
    </group>
    <!-- Event group -->
    <group xml:id="events">
        <label xml:lang="it">Storia delle operazioni</label>
        <label xml:lang="en">Survey and Operation History</label>
        <label xml:lang="es">Historia de la encuesta y la operación</label>
        <element xml:id="history" isMandatory="true" isMultiple="true">
            <label xml:lang="it">Indagini e operazioni a bordo</label>
            <label xml:lang="en">Survey and operation on board</label>
            <label xml:lang="es">Encuesta y funcionamiento a bordo</label>
            <help xml:lang="it">Indagini e operazioni che vengono svolte sulla nave durante la navigazione (es. partenza della nave, ancoraggi in porto, operazioni di campionamento ecc.)</help>
            <help xml:lang="en">Survey and operation conducted during the cruise (e.g. berths in the port, sampling operations, etc.)</help>
            <help xml:lang="es">
                Encuesta y operación llevada a cabo durante el crucero (por ejemplo, atraques en el puerto, las operaciones de muestreo, etc.)</help>
            <hasRoot>/sml:EventList</hasRoot>
            <produces>
                <item hasIndex="1" xml:id="history_1" isFixed="false" hasDatatype="text">
                    <label xml:lang="it">Descrizione</label>
                    <label xml:lang="en">Description</label>
                    <label xml:lang="es">Descripción</label>
                    <help xml:lang="it">Breve descrizione</help>
                    <help xml:lang="en">Brief description</help>
                    <help xml:lang="es">Breve descripción</help>
                    <hasPath>sml:event/sml:Event/swe:description</hasPath>
                </item>
                <!-- TO DO: in this moment only date and not time -->
                <item hasIndex="2" xml:id="history_2" isFixed="false" hasDatatype="dateRange">
                    <label xml:lang="en">Foo</label>
                    <label xml:lang="it">Data</label>
                    <label xml:lang="es">Datos</label>
                    <start>
                        <label xml:lang="en">Begin date</label>
                        <label xml:lang="it">Data inizio</label>
                        <label xml:lang="es">Fecha de inicio</label>
                        <hasPath>sml:event/sml:Event/sml:time/gml:TimePeriod/gml:beginPosition</hasPath>
                    </start>
                    <end>
                        <label xml:lang="en">End date</label>
                        <label xml:lang="it">Data fine</label>
                        <label xml:lang="es">Fecha final</label>
                        <hasPath>sml:event/sml:Event/sml:time/gml:TimePeriod/gml:endPosition</hasPath>
                    </end>
                </item>
                <item hasIndex="3" xml:id="history_3" isFixed="true" hasDatatype="autonumber">
                    <hasPath>sml:event/sml:Event/sml:time/gml:TimePeriod/@gml:id</hasPath>
                    <hasValue>operation_interval_</hasValue>
                </item>
                <item hasIndex="4" xml:id="history_4" isFixed="true" hasDatatype="string">
                    <hasPath>sml:event/sml:Event/sml:property/@xlink:title</hasPath>
                    <hasValue>link to vessel description</hasValue>
                </item>
                <item hasIndex="5" xml:id="history_5" isFixed="false" hasDatatype="text">
                    <label xml:lang="en">URI of the vessel description</label>
                    <label xml:lang="it">URI alla descrizione della nave</label>
                    <label xml:lang="es">URI de la descripción del buque</label>
                    <hasPath>sml:event/sml:Event/sml:property/@xlink:role</hasPath>
                </item>           
                <item hasIndex="6" xml:id="history_6" isFixed="true"
                    datasource="devices" hasDatatype="select" field="c">
                    <hasPath>sml:event/sml:Event/sml:property/@xlink:href</hasPath>
                </item>
            </produces>
        </element>
    </group>
</template>
